/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/_layout'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as protectedHomeRouteImport } from './routes/(protected)/home'
import { Route as onboardingOnboardingRouteImport } from './routes/(onboarding)/onboarding'
import { Route as publicauthLayoutRouteImport } from './routes/(public)/(auth)/_layout'
import { Route as publicauthSsoCallbackRouteImport } from './routes/(public)/(auth)/sso-callback'
import { Route as publicauthRegisterRouteImport } from './routes/(public)/(auth)/register'
import { Route as publicauthLoginRouteImport } from './routes/(public)/(auth)/login'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const protectedHomeRoute = protectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const onboardingOnboardingRoute = onboardingOnboardingRouteImport.update({
  id: '/(onboarding)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthLayoutRoute = publicauthLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicauthSsoCallbackRoute = publicauthSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => publicauthLayoutRoute,
} as any)
const publicauthRegisterRoute = publicauthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => publicauthLayoutRoute,
} as any)
const publicauthLoginRoute = publicauthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicauthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/home': typeof protectedHomeRoute
  '/login': typeof publicauthLoginRoute
  '/register': typeof publicauthRegisterRoute
  '/sso-callback': typeof publicauthSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/home': typeof protectedHomeRoute
  '/login': typeof publicauthLoginRoute
  '/register': typeof publicauthRegisterRoute
  '/sso-callback': typeof publicauthSsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(public)/(auth)': typeof publicauthLayoutRouteWithChildren
  '/(onboarding)/onboarding': typeof onboardingOnboardingRoute
  '/(protected)/home': typeof protectedHomeRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/(auth)/login': typeof publicauthLoginRoute
  '/(public)/(auth)/register': typeof publicauthRegisterRoute
  '/(public)/(auth)/sso-callback': typeof publicauthSsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/home'
    | '/login'
    | '/register'
    | '/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/home' | '/login' | '/register' | '/sso-callback'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)'
    | '/(public)/(auth)'
    | '/(onboarding)/onboarding'
    | '/(protected)/home'
    | '/(public)/'
    | '/(public)/(auth)/login'
    | '/(public)/(auth)/register'
    | '/(public)/(auth)/sso-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
  onboardingOnboardingRoute: typeof onboardingOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(protected)/home': {
      id: '/(protected)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof protectedHomeRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(onboarding)/onboarding': {
      id: '/(onboarding)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof onboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)': {
      id: '/(public)/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicauthLayoutRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/(auth)/sso-callback': {
      id: '/(public)/(auth)/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof publicauthSsoCallbackRouteImport
      parentRoute: typeof publicauthLayoutRoute
    }
    '/(public)/(auth)/register': {
      id: '/(public)/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicauthRegisterRouteImport
      parentRoute: typeof publicauthLayoutRoute
    }
    '/(public)/(auth)/login': {
      id: '/(public)/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicauthLoginRouteImport
      parentRoute: typeof publicauthLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedHomeRoute: typeof protectedHomeRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedHomeRoute: protectedHomeRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

interface publicauthLayoutRouteChildren {
  publicauthLoginRoute: typeof publicauthLoginRoute
  publicauthRegisterRoute: typeof publicauthRegisterRoute
  publicauthSsoCallbackRoute: typeof publicauthSsoCallbackRoute
}

const publicauthLayoutRouteChildren: publicauthLayoutRouteChildren = {
  publicauthLoginRoute: publicauthLoginRoute,
  publicauthRegisterRoute: publicauthRegisterRoute,
  publicauthSsoCallbackRoute: publicauthSsoCallbackRoute,
}

const publicauthLayoutRouteWithChildren =
  publicauthLayoutRoute._addFileChildren(publicauthLayoutRouteChildren)

interface publicLayoutRouteChildren {
  publicauthLayoutRoute: typeof publicauthLayoutRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicauthLayoutRoute: publicauthLayoutRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
  onboardingOnboardingRoute: onboardingOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
