/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as onboardingLayoutRouteImport } from './routes/(onboarding)/_layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as onboardingOnboardingRouteImport } from './routes/(onboarding)/onboarding'
import { Route as authSsoCallbackRouteImport } from './routes/(auth)/sso-callback'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appHomeLayoutRouteImport } from './routes/(app)/home/_layout'
import { Route as appHomeIndexRouteImport } from './routes/(app)/home/index'
import { Route as appPostIdRouteImport } from './routes/(app)/post/$id'
import { Route as appHomeFeedRouteImport } from './routes/(app)/home/feed'
import { Route as appHomeDiscoverRouteImport } from './routes/(app)/home/discover'
import { Route as appProfileUsernameLayoutRouteImport } from './routes/(app)/profile/$username/_layout'
import { Route as appProfileUsernameIndexRouteImport } from './routes/(app)/profile/$username/index'
import { Route as appProfileUsernameRepliesRouteImport } from './routes/(app)/profile/$username/replies'
import { Route as appProfileUsernameMentionsRouteImport } from './routes/(app)/profile/$username/mentions'
import { Route as appProfileUsernameLikesRouteImport } from './routes/(app)/profile/$username/likes'

const onboardingLayoutRoute = onboardingLayoutRouteImport.update({
  id: '/(onboarding)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const onboardingOnboardingRoute = onboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => onboardingLayoutRoute,
} as any)
const authSsoCallbackRoute = authSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => authLayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const appHomeLayoutRoute = appHomeLayoutRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appLayoutRoute,
} as any)
const appHomeIndexRoute = appHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appHomeLayoutRoute,
} as any)
const appPostIdRoute = appPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => appLayoutRoute,
} as any)
const appHomeFeedRoute = appHomeFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => appHomeLayoutRoute,
} as any)
const appHomeDiscoverRoute = appHomeDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => appHomeLayoutRoute,
} as any)
const appProfileUsernameLayoutRoute =
  appProfileUsernameLayoutRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appProfileUsernameIndexRoute = appProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProfileUsernameLayoutRoute,
} as any)
const appProfileUsernameRepliesRoute =
  appProfileUsernameRepliesRouteImport.update({
    id: '/replies',
    path: '/replies',
    getParentRoute: () => appProfileUsernameLayoutRoute,
  } as any)
const appProfileUsernameMentionsRoute =
  appProfileUsernameMentionsRouteImport.update({
    id: '/mentions',
    path: '/mentions',
    getParentRoute: () => appProfileUsernameLayoutRoute,
  } as any)
const appProfileUsernameLikesRoute = appProfileUsernameLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => appProfileUsernameLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authIndexRoute
  '/home': typeof appHomeLayoutRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/sso-callback': typeof authSsoCallbackRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/profile/$username': typeof appProfileUsernameLayoutRouteWithChildren
  '/home/discover': typeof appHomeDiscoverRoute
  '/home/feed': typeof appHomeFeedRoute
  '/post/$id': typeof appPostIdRoute
  '/home/': typeof appHomeIndexRoute
  '/profile/$username/likes': typeof appProfileUsernameLikesRoute
  '/profile/$username/mentions': typeof appProfileUsernameMentionsRoute
  '/profile/$username/replies': typeof appProfileUsernameRepliesRoute
  '/profile/$username/': typeof appProfileUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/sso-callback': typeof authSsoCallbackRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/home/discover': typeof appHomeDiscoverRoute
  '/home/feed': typeof appHomeFeedRoute
  '/post/$id': typeof appPostIdRoute
  '/home': typeof appHomeIndexRoute
  '/profile/$username/likes': typeof appProfileUsernameLikesRoute
  '/profile/$username/mentions': typeof appProfileUsernameMentionsRoute
  '/profile/$username/replies': typeof appProfileUsernameRepliesRoute
  '/profile/$username': typeof appProfileUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appLayoutRouteWithChildren
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(onboarding)': typeof onboardingLayoutRouteWithChildren
  '/(app)/home': typeof appHomeLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/sso-callback': typeof authSsoCallbackRoute
  '/(onboarding)/onboarding': typeof onboardingOnboardingRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/profile/$username': typeof appProfileUsernameLayoutRouteWithChildren
  '/(app)/home/discover': typeof appHomeDiscoverRoute
  '/(app)/home/feed': typeof appHomeFeedRoute
  '/(app)/post/$id': typeof appPostIdRoute
  '/(app)/home/': typeof appHomeIndexRoute
  '/(app)/profile/$username/likes': typeof appProfileUsernameLikesRoute
  '/(app)/profile/$username/mentions': typeof appProfileUsernameMentionsRoute
  '/(app)/profile/$username/replies': typeof appProfileUsernameRepliesRoute
  '/(app)/profile/$username/': typeof appProfileUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/onboarding'
    | '/profile/$username'
    | '/home/discover'
    | '/home/feed'
    | '/post/$id'
    | '/home/'
    | '/profile/$username/likes'
    | '/profile/$username/mentions'
    | '/profile/$username/replies'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/onboarding'
    | '/home/discover'
    | '/home/feed'
    | '/post/$id'
    | '/home'
    | '/profile/$username/likes'
    | '/profile/$username/mentions'
    | '/profile/$username/replies'
    | '/profile/$username'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(onboarding)'
    | '/(app)/home'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/sso-callback'
    | '/(onboarding)/onboarding'
    | '/(auth)/'
    | '/(app)/profile/$username'
    | '/(app)/home/discover'
    | '/(app)/home/feed'
    | '/(app)/post/$id'
    | '/(app)/home/'
    | '/(app)/profile/$username/likes'
    | '/(app)/profile/$username/mentions'
    | '/(app)/profile/$username/replies'
    | '/(app)/profile/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
  authLayoutRoute: typeof authLayoutRouteWithChildren
  onboardingLayoutRoute: typeof onboardingLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(onboarding)': {
      id: '/(onboarding)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof onboardingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(onboarding)/onboarding': {
      id: '/(onboarding)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof onboardingOnboardingRouteImport
      parentRoute: typeof onboardingLayoutRoute
    }
    '/(auth)/sso-callback': {
      id: '/(auth)/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof authSsoCallbackRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(app)/home': {
      id: '/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeLayoutRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/home/': {
      id: '/(app)/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof appHomeIndexRouteImport
      parentRoute: typeof appHomeLayoutRoute
    }
    '/(app)/post/$id': {
      id: '/(app)/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof appPostIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/home/feed': {
      id: '/(app)/home/feed'
      path: '/feed'
      fullPath: '/home/feed'
      preLoaderRoute: typeof appHomeFeedRouteImport
      parentRoute: typeof appHomeLayoutRoute
    }
    '/(app)/home/discover': {
      id: '/(app)/home/discover'
      path: '/discover'
      fullPath: '/home/discover'
      preLoaderRoute: typeof appHomeDiscoverRouteImport
      parentRoute: typeof appHomeLayoutRoute
    }
    '/(app)/profile/$username': {
      id: '/(app)/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof appProfileUsernameLayoutRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/profile/$username/': {
      id: '/(app)/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof appProfileUsernameIndexRouteImport
      parentRoute: typeof appProfileUsernameLayoutRoute
    }
    '/(app)/profile/$username/replies': {
      id: '/(app)/profile/$username/replies'
      path: '/replies'
      fullPath: '/profile/$username/replies'
      preLoaderRoute: typeof appProfileUsernameRepliesRouteImport
      parentRoute: typeof appProfileUsernameLayoutRoute
    }
    '/(app)/profile/$username/mentions': {
      id: '/(app)/profile/$username/mentions'
      path: '/mentions'
      fullPath: '/profile/$username/mentions'
      preLoaderRoute: typeof appProfileUsernameMentionsRouteImport
      parentRoute: typeof appProfileUsernameLayoutRoute
    }
    '/(app)/profile/$username/likes': {
      id: '/(app)/profile/$username/likes'
      path: '/likes'
      fullPath: '/profile/$username/likes'
      preLoaderRoute: typeof appProfileUsernameLikesRouteImport
      parentRoute: typeof appProfileUsernameLayoutRoute
    }
  }
}

interface appHomeLayoutRouteChildren {
  appHomeDiscoverRoute: typeof appHomeDiscoverRoute
  appHomeFeedRoute: typeof appHomeFeedRoute
  appHomeIndexRoute: typeof appHomeIndexRoute
}

const appHomeLayoutRouteChildren: appHomeLayoutRouteChildren = {
  appHomeDiscoverRoute: appHomeDiscoverRoute,
  appHomeFeedRoute: appHomeFeedRoute,
  appHomeIndexRoute: appHomeIndexRoute,
}

const appHomeLayoutRouteWithChildren = appHomeLayoutRoute._addFileChildren(
  appHomeLayoutRouteChildren,
)

interface appProfileUsernameLayoutRouteChildren {
  appProfileUsernameLikesRoute: typeof appProfileUsernameLikesRoute
  appProfileUsernameMentionsRoute: typeof appProfileUsernameMentionsRoute
  appProfileUsernameRepliesRoute: typeof appProfileUsernameRepliesRoute
  appProfileUsernameIndexRoute: typeof appProfileUsernameIndexRoute
}

const appProfileUsernameLayoutRouteChildren: appProfileUsernameLayoutRouteChildren =
  {
    appProfileUsernameLikesRoute: appProfileUsernameLikesRoute,
    appProfileUsernameMentionsRoute: appProfileUsernameMentionsRoute,
    appProfileUsernameRepliesRoute: appProfileUsernameRepliesRoute,
    appProfileUsernameIndexRoute: appProfileUsernameIndexRoute,
  }

const appProfileUsernameLayoutRouteWithChildren =
  appProfileUsernameLayoutRoute._addFileChildren(
    appProfileUsernameLayoutRouteChildren,
  )

interface appLayoutRouteChildren {
  appHomeLayoutRoute: typeof appHomeLayoutRouteWithChildren
  appProfileUsernameLayoutRoute: typeof appProfileUsernameLayoutRouteWithChildren
  appPostIdRoute: typeof appPostIdRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appHomeLayoutRoute: appHomeLayoutRouteWithChildren,
  appProfileUsernameLayoutRoute: appProfileUsernameLayoutRouteWithChildren,
  appPostIdRoute: appPostIdRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

interface authLayoutRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authSsoCallbackRoute: typeof authSsoCallbackRoute
  authIndexRoute: typeof authIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authSsoCallbackRoute: authSsoCallbackRoute,
  authIndexRoute: authIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface onboardingLayoutRouteChildren {
  onboardingOnboardingRoute: typeof onboardingOnboardingRoute
}

const onboardingLayoutRouteChildren: onboardingLayoutRouteChildren = {
  onboardingOnboardingRoute: onboardingOnboardingRoute,
}

const onboardingLayoutRouteWithChildren =
  onboardingLayoutRoute._addFileChildren(onboardingLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
  authLayoutRoute: authLayoutRouteWithChildren,
  onboardingLayoutRoute: onboardingLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
