spring:
    datasource:
        name: echo
        url: jdbc:postgresql://localhost:5432/echo
        username: admin
        password: pw123

    data:
        redis:
            host: localhost
            port: 6379

    sql:
        init:
            schema-locations: classpath:sql/schema/schema-*.sql
            mode: always

    docker:
        compose:
            lifecycle-management: start-only

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

cloudinary:
    cloud-name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

cors:
    allowed-origins: http://localhost:5173 # comma-separated values
