spring:
    docker:
        compose:
            lifecycle-management: start-only
    datasource:
        name: echo
        url: jdbc:postgresql://localhost:5432/echo
        username: admin
        password: pw123
    sql:
        init:
            mode: always
    data:
        redis:
            host: http://localhost:6379
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

cors:
    allowed-origins: http://localhost:5173 # comma-separated values
