spring:
    application:
        name: echo-api

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none

    flyway:
        enabled: true
        locations: 
            - classpath:db/migration
            - classpath:db/repeatable

springdoc:
    api-docs:
        path: /openapi
    swagger-ui:
        path: /swagger-ui
