server:
    port: ${PORT}

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${CLERK_ISSUER_URI:}
                    jwk-set-uri: ${CLERK_JWK_SET_URI:}

    datasource:
        url: ${DATASOURCE_URL:}
        username: ${DATASOURCE_USERNAME:}
        password: ${DATASOURCE_PASSWORD:}

clerk:
    secret-key: ${CLERK_SECRET_KEY:}
    webhook-signing-secret: ${CLERK_WEBHOOK_SIGNING_SECRET:}

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}