spring:

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${DEV_CLERK_ISSUER_URI}
                    jwk-set-uri: ${DEV_CLERK_JWK_SET_URI}
    
    datasource:
        name: ${DEV_DATASOURCE_NAME}
        url: ${DEV_DATASOURCE_URL}
        username: ${DEV_DATASOURCE_USERNAME}
        password: ${DEV_DATASOURCE_PASSWORD}

    sql:
        init:
            mode: always

    docker:
        compose:
            lifecycle-management: start-only

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

cors:
    allowed-origins: ${DEV_CORS_ALLOWED_ORIGINS}

clerk:
    secret-key: ${DEV_CLERK_SECRET_KEY}
    webhook-signing-secret: ${DEV_CLERK_WEBHOOK_SIGNING_SECRET}

logging:
    level:
        org:
            springframework:
                web: DEBUG
                security: TRACE
