server:
    port: 8080

spring:
    config:
        import: optional:file:.env.dev[.properties]

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${CLERK_ISSUER_URI:}
                    jwk-set-uri: ${CLERK_JWK_SET_URI:}
    
    datasource:
        url: ${DATASOURCE_URL:}
        name: ${DATASOURCE_NAME:}
        username: ${DATASOURCE_USERNAME:}
        password: ${DATASOURCE_PASSWORD:}

    sql:
        init:
            mode: always

    docker:
        compose:
            lifecycle-management: start-only

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

clerk:
    secret-key: ${CLERK_SECRET_KEY:}
    webhook-signing-secret: ${CLERK_WEBHOOK_SIGNING_SECRET:}

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}

logging:
    level:
        org:
            springframework:
                web: DEBUG
                security: TRACE
