spring:
    application:
        name: echo-api

    sql:
        init:
            mode: never # default to disabled, override where required
            schema-locations:
                - classpath:sql/schema/*.sql
                - classpath:sql/function/*.sql
                - classpath:sql/trigger/*.sql

cloudinary:
    cloud-name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
