spring:
    sql:
        init:
            mode: always

    datasource:
        name: echo
        url: jdbc:postgresql://localhost:5432/echo
        username: admin
        password: pw123

    docker:
        compose:
            lifecycle-management: start-only

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

cloudinary:
    cloud-name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

cors:
    allowed-origins: http://localhost:5173 # comma-separated values

logging:
    level:
        org:
            springframework:
                jdbc:
                    core: DEBUG
