server:
    port: 8080

spring:
    application:
        name: echo-api

    profiles:
        active: dev

    config:
        import: optional:file:.env[.properties]

    sql:
        init:
            mode: never # default to disabled, override per-profile
            schema-locations:
                - classpath:sql/schema/*.sql
                - classpath:sql/function/*.sql
                - classpath:sql/trigger/*.sql

cloudinary:
    cloud-name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
