name: API - Deploy to Production

on:
    workflow_dispatch: # Manually run workflow from GH repository/CLI
    push:
        tags: [api@v*]

defaults:
    run:
        working-directory: api

env:
    RAILWAY_SERVICE_ID: 1eb5003b-188d-48d5-977b-5f55b02b01e6
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
    deploy-production:
        runs-on: ubuntu-latest 

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: 'temurin'
                  cache: gradle

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Build (skip tests)
              run: ./gradlew assemble

            - name: Install Railway CLI
              run: npm i -g @railway/cli
              # docs: https://docs.railway.com/reference/cli-api

            - name: Railway Deploy
              run: railway up --service=$RAILWAY_SERVICE_ID
