name: CI Pipeline

on:
    pull_request:
        branches:
            - dev
            - main

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            # Checkout code
            - name: Checkout Code
              uses: actions/checkout@v4

            # Set up JDK
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: 'temurin'
                  cache: gradle

            # Set up Gradle
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            # Run tests
            - name: Build & Test w/ Gradle Wrapper
              run: ./gradlew clean build --scan --stacktrace

            # Upload test results
            - name: Upload Test Results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: test-results
                  path: build/test-results
