name: Validate Dev PR Title

on:
    pull_request:
        branches:
            - dev
        types: [opened, edited, reopened, synchronize]

jobs:
    check-pr-title:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate PR title
              run: |

                  # Disable history expansion to allow '!' in title
                  set +H

                  # Pattern
                  PATTERN="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?:"

                  # Check if the PR title matches the expected pattern
                  if [[ ! '${{ github.event.pull_request.title }}' =~ $PATTERN ]]; then
                  echo "❌ PR title must follow the Conventional Commits format!"
                  echo ""
                  echo "Expected title format:"
                  echo "<type>[optional scope]: <description>"
                  echo ""
                  echo "Valid types: build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test"
                  echo "For breaking changes, use: <type>[optional scope]!: <description>"
                  echo ""
                  echo "See: https://www.conventionalcommits.org/en/v1.0.0/ for more details."
                  exit 1
                  fi

                  # Print success message if the title is valid
                  echo "✅ PR title follows Conventional Commits format."
