name: Validate Dev PR Title

on:
    pull_request:
        branches:
            - dev
        types: [opened, edited, reopened, synchronize]

jobs:
    check-pr-title:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate PR title
              run: |

                  # Pattern
                  PATTERN="^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)([!])?:"

                  # Check if the PR title matches the expected pattern
                  if [[ ! '${{ github.event.pull_request.title }}' =~ $PATTERN ]]; then
                  echo "❌ PR title must follow the Conventional Commits format!"
                  echo ""
                  echo "Expected title format:"
                  echo "<type>[optional scope]: <description>"
                  echo ""
                  echo "Valid types: feat, fix, docs, style, refactor, perf, test, chore, ci, build"
                  echo "For breaking changes, use: <type>!: <description>"
                  echo ""
                  echo "See: https://www.conventionalcommits.org/en/v1.0.0/ for more details."
                  exit 1
                  fi

                  # Print success message if the title is valid (optional)
                  echo "✅ PR title follows Conventional Commits format."
